modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
issueTrackerURL="http://github.com/Xbony2/HuesoDeWiki"

[[mods]]
modId="huesodewiki"
version="${file.jarVersion}"
displayName="HuesoDeWiki"
displayURL="https://www.curseforge.com/minecraft/mc-mods/huesodewiki"
authors="Xbony2, Hubry, TheSatanicSanta"
description='''
A small utility mod for editors of the Official FTB Wiki. It automatically creates a base page in the clipboard from in-game items.
'''

[[dependencies.huesodewiki]]
	modId="forge"
	mandatory=true
	versionRange="[40,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.huesodewiki]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.19,)"
	ordering="NONE"
	side="BOTH"
